### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by DenaryDev** [songoda/SongodaCore#37]

**Comment by FlynnLG** [comment]
Please update! 1.18.2 has been released for several weeks.

**Comment by SpraxDev** [comment]
We are already working on 1.18.2 support and testing it. You can keep up-to-date about that on our Discord https://songoda.com/discord or https://docs.google.com/spreadsheets/d/1fsKSdrXz_92vtGHHKPoS0R5K_vcr8BvM8OMEcbBtL7c/edit

**Comment by SpraxDev** [comment]
1.18.2 support is now part of v2.6.12, further bug fixes might be required
